### ISSUE TITLE
Performance of Pyranet on MPII

### ISSUE THREAD

**Issue by HenryJunW** [Naman-ntc/Pytorch-Human-Pose-Estimation#5]
Hello, impressive work. I am wondering whether you can post the results on MPII of the Pyranet. If possible, would you mind posting the pre-trained model as well. Thanks.

**Comment by Naman-ntc** [comment]
Hi,
I have tried training Pyranet on MPII dataset but was unable to reproduce official results. It might probably be difference in training routine or data augmentation or some subtle difference in architecture of model written in `Lua-Torch` or `Pytorch`. 
I will hopefully try to train it again sometime in future but it doesn't seem possible currently due to other commitments. Feel free to try to train it on your own!
